version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: codepad_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - codepad_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: codepad_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - codepad_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: codepad_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codepad
      MYSQL_USER: codepaduser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - codepad_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  codepad_network:

volumes:
  db_data:
